production:
 default_url_options:
  host: ^^domain.fqdn^^
 email_delivery:
  delivery_method: :smtp
  smtp_settings:
   address: ^^configuration.stmp_host^^
   port: 25
   domain: ^^domain.identifier^^
   enable_starttls_auto : false
   attachments_storage_path: /tmp
